kind: pipeline
name: zeek

platform:
  arch: arm64
  
clone:
  disable: true

steps:
- name: clone
  image: ubuntu
  commands:
  - git clone git@github.com:markh15/zeek.git .

- name: build
  image: gcc
  commands:
  - uname -a
  - ./configure
  - make
