kind: pipeline
name: zeek

platform:
  arch: arm64
  
steps:
- name: submodules
  image: alpine/git
  commands:
  - git submodule update --recursive --init

- name: build
  image: gcc
  commands:
  - uname -a
  - git submodule update --recursive --init
  - ./configure
  - make
