kind: pipeline
name: zeek

platform:
  arch: arm64
  
steps:
- name: submodules
  image: ubuntu/git
  commands:
  - git submodule update --recursive --init
  
steps:
- name: uname
  image: ubuntu
  commands:
  - uname -a

- name: build
  image: ubuntu
  commands:
  - pwd
  - ls -l
  - ./configure
  - make
