kind: pipeline
name: zeek

platform:
  arch: arm64

clone:
  disable: true

steps:
- name: clone
  image: alpine/git
  commands:
  - git clone --recursive https://github.com/zeek/zeek
  - git checkout $DRONE_COMMIT
  
steps:
- name: uname
  image: ubuntu
  commands:
  - uname -a

- name: build
  image: ubuntu
  commands:
  - pwd
  - ls -l
  - ./configure
  - make
