kind: pipeline
name: zeek

platform:
  arch: arm64
  
steps:
- name: uname
  image: ubuntu
  commands:
  - uname -a

- name: build
  image: ubuntu
  commands:
  - pwd
  - ls -l
  - cd /drone/src && git submodule update --recursive --init
  - ./configure
  - make
