kind: pipeline
name: zeek

platform:
  arch: arm64
  
clone:
  disable: true

steps:
- name: clone
  image: centos
  commands:
  - yum install -y git
  - git clone --recursive https://github.com/markh15/zeek.git .

- name: build
  image: gcc
  commands:
  - uname -a
  - apt-get update && apt-get install -y cmake
  - ./configure
  - make
