kind: pipeline
name: zeek

platform:
  arch: arm64

steps:
- name: submodules
  image: ubuntu
  commands:
  - git submodule init
  - git submodule update --recursive --remote
  
steps:
- name: uname
  image: ubuntu
  commands:
  - uname -a

- name: build
  image: ubuntu
  commands:
  - pwd
  - ls -l
  - ./configure
  - make
